[package]
name = "caws"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.23.0", features = ["full"] }
serde = "1.0.152"
serde_json = "1.0.91"
log = "0.4.17"
lambda_runtime = "0.7.2"